services:
  - type: web
    name: desafioautou
    env: python
    region: ohio 
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NLTK_DATA
        value: /opt/render/.nltk_data
    autoDeploy: true
    plan: free